version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "youngkiu"
    assignees:
      - "youngkiu"
    open-pull-requests-limit: 5
