version: '3'

services:
  app:
    container_name: app
    image: nestjs-oauth
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${APP_PORT}:3000
    environment:
      MIXPANEL_TOKEN: ${MIXPANEL_TOKEN}
      SENTRY_DSN: ${SENTRY_DSN}
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}
      SENDGRID_EMAIL_ADDRESS: ${SENDGRID_EMAIL_ADDRESS}
      COOKIE_SECRET: ${COOKIE_SECRET}
      JWT_SECRET: ${JWT_SECRET}
      AUTH_COOKIE_NAME: ${AUTH_COOKIE_NAME}
      KAKAO_REST_API_KEY: ${KAKAO_REST_API_KEY}
      KAKAO_REDIRECT_URI: ${KAKAO_REDIRECT_URI}
      KAKAO_CLIENT_SECRET: ${KAKAO_CLIENT_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_REDIRECT_URI: ${GOOGLE_REDIRECT_URI}
      DATABASE_URL: "mongodb://${MONGO_USER}:${MONGO_PW}@local-mongo:27017/${MONGO_DB}?authSource=admin"
      PORT: 3000
      WAIT_HOSTS: mongo:27017
    command:
      - bash
      - -c
      - | # https://yaml-multiline.info/
        /wait &&
        npm run start
    depends_on:
      - mongo

  mongo:
    container_name: local-mongo
    image: mongo:5.0.15
    restart: always
    ports:
      - ${MONGO_PORT}:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PW}
      - MONGO_INITDB_DATABASE=${MONGO_DB}
    volumes:
      - ./mongodb/:/data/db/
      - ./:/opt/keyfile/
    command: "--bind_ip_all --keyFile /opt/keyfile/keyfile --replSet rs0"
