version: '3'

services:
  app:
    container_name: app
    image: nestjs-oauth
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${APP_PORT}:3000
    environment:
      PORT: 3000
      WAIT_HOSTS: mongo:27017
    command:
      - bash
      - -c
      - | # https://yaml-multiline.info/
        /wait &&
        npm run start
    depends_on:
      - mongo

  mongo:
    container_name: local-mongo
    image: mongo:5.0.15
    restart: always
    ports:
      - ${MONGO_PORT}:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PW}
      - MONGO_INITDB_DATABASE=${MONGO_DB}
    volumes:
      - ./mongodb/:/data/db/
      - ./:/opt/keyfile/
    command: "--bind_ip_all --keyFile /opt/keyfile/keyfile --replSet rs0"
