version: '3'

services:
  app:
    container_name: app
    image: nestjs-oauth
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${APP_PORT}:3000
    environment:
      PORT: 3000
      MONGO_USER: ${MONGO_USER}
      MONGO_PW: ${MONGO_PW}
      MONGO_DB: ${MONGO_DB}
      MONGO_HOST: local-mongo
      MONGO_PORT: 27017
      WAIT_HOSTS: mongo:27017
    command:
      - bash
      - -c
      - | # https://yaml-multiline.info/
        /wait &&
        npm run start
    depends_on:
      - mongo

  mongo:
    container_name: local-mongo
    image: mongo:6.0.5
    restart: always
    ports:
      - ${MONGO_PORT}:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PW}
      - MONGO_INITDB_DATABASE=${MONGO_DB}
    volumes:
      - ./mongodb:/data/db
