name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DATABASE_URL: "mongodb://localhost:27017/test"
  JWT_SECRET: "test-secret"
  KAKAO_REST_API_KEY: "test-rest-api-key"
  KAKAO_CLIENT_ID: "test-client-id"
  KAKAO_CLIENT_SECRET: "test-client-secret"
  KAKAO_REDIRECT_URI: "http://localhost:3000/auth/kakao/callback"
  GOOGLE_CLIENT_ID: "test-client-id"
  GOOGLE_CLIENT_SECRET: "test-client-secret"
  GOOGLE_REDIRECT_URI: "http://localhost:3000/auth/google/callback"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.runCommand(\"ping\")'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Lint
      run: npm run lint

    - name: Run tests
      run: npm run test

    - name: Run e2e tests
      run: npm run test:e2e

    - name: Start application test
      run: |
        npm run build
        npm run start:prod &
        sleep 10
        curl -f http://localhost:3000 || exit 1
